# Generated by Django 3.0.2 on 2020-01-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('level', models.IntegerField()),
                ('sub_level', models.IntegerField()),
                ('sub_sub_level', models.IntegerField()),
                ('sub_sub_sub_level', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('available', models.BooleanField()),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=300, unique=True)),
                ('image', models.URLField()),
                ('sublevel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'db_table': 'Products',
                'ordering': ['-id'],
            },
        ),
    ]
